# Site settings
title: Taewoo's Blog
email: qkqnrpa@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: First, Let's start anything.

# Social icons
facebook: jintaewoo
linkedin: username
github: taewoojin
deviantart: username
codepen: username

# Build settings
markdown: kramdown

footer: email - qkqnrpa@gmail.com
# paginate: 10

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
